[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_NODE_ENV = "production"